#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing PID
# Trap signals
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM

# Create PID file
echo $$ > /var/run/myscript.pid

# Display messages indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

# Delete PID file and terminate on SIGQUIT or SIGTERM signals
trap 'rm -f /var/run/myscript.pid && exit' SIGQUIT SIGTERM

# Ensure the script does not terminate prematurely
sleep infinity
