#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM SIGQUI
echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
